language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
after_script:
  - npm run coveralls
git:
  depth: 1
branches:
  only:
    - master